### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-CONSTRUMIX#5]
- [x] "_**A falta de um sistema**_ centralizado dificulta o rastreamento do histórico de movimentação..." - _não é a falta de um sistema, é o uso de planilha e anotações em papel_
- [x] "e também não oferece recursos de _**geração de relatórios e extratos**_, o que pode dificultar análises de desempenho do estoque e a identificação de tendências ou problemas." - _dificultado a elaboração de relatórios, análises e identificação de tendências_
- [x] **Qual é o problema?** dificuldade de gerenciamento ou falta de confiança nos dados?

![image](https://github.com/mdsreq-fga-unb/2024.1-CONSTRUMIX/assets/68402547/8ae71d25-f717-483f-9c38-8a15e9c84883)

**Comment by Carlos-kadu** [comment]
As correções foram realizadas.
